language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix: 
    - JULIAVERSION="julianightlies" 
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - sudo apt-get install protobuf-compiler
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("ProtoBuf"))`); Pkg.pin("ProtoBuf"); Pkg.resolve()'
  - julia -e 'using ProtoBuf; @assert isdefined(:ProtoBuf); @assert typeof(ProtoBuf) === Module'
  - julia ./test/testcodec.jl
  - export PATH=./plugin:$PATH; ./test/testprotoc.sh
