language: julia
julia:
  - 0.6
  - nightly
notifications:
  email: false
sudo: required
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install protobuf-compiler
  - sudo apt-get install curl
  - sudo ./test/setup_protoc3.sh
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("ProtoBuf"); Pkg.test("ProtoBuf"; coverage=true)'
  - COVERAGE="--code-coverage=user --inline=no" PATH=./plugin:$PATH ./test/testprotoc.sh
  - COVERAGE="--code-coverage=user --inline=no" PATH=./plugin:$PATH PROTOC=/proto3/protobuf-3.0.0-beta-4/install/bin/protoc ./test/testprotoc.sh
after_success:
  - julia -e 'cd(Pkg.dir("ProtoBuf")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder());'
  - julia -e 'cd(Pkg.dir("ProtoBuf")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
