language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix: 
    - JULIAVERSION="juliareleases" 
    - JULIAVERSION="julianightlies" 
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - sudo apt-get install protobuf-compiler
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("Protobuf"))`); Pkg.pin("Protobuf"); Pkg.resolve()'
  - julia -e 'using Protobuf; @assert isdefined(:Protobuf); @assert typeof(Protobuf) === Module'
  - julia ./test/testcodec.jl
  - ./test/testprotoc.sh
